export const GOAL_CREATED = "GOAL_CREATED";
export const CREATE_GOAL_SUCCESS = "CREATE_GOAL_SUCCESS";
export const UPDATE_GOAL_SUCCESS = "UPDATE_GOAL_SUCCESS";
export const GOAL_TOGGLED = "GOAL_TOGGLED";
export const DELETE_GOAL_SUCCCESS = "DELETE_GOAL_SUCCCESS";
export const LOAD_GOALS_SUCCESS = "LOAD_GOALS_SUCCESS";
